ignore = [
    "NuVecMtxTranslate",
    "NuVecMtxRotateValX",
    "NuVecMtxRotateValY",
    "NuVecMtxRotateValZ",
    "NuVecMtxRotateH",
    "NuVecMtxScale",
    "NuVecInvMtxTranslate",
    "NuVecInvMtxRotateValX",
    "NuVecInvMtxRotateValY",
    "NuVecInvMtxRotateValZ",
    "NuVecInvMtxScale",
    "NuVecRotateYValX",
    "NuVecInvScale",
    "NuVecCrossRel",
    "NuVecMagXZ",
    "NuVecCompareTolerance",
    "NuVecConvertToIntVU0",
    "NuVecInvMtxTransformVU0",
    "_Z11NuVecToRGBAP7nuvec_sf",
    "NuVecNormVU0",
    "NuVecDiffVU0",
    "NuVecDiffSqrVU0",
]
